# Site settings
protocol: "https:"
domain: "cl305.github.io"
url: "https://cl305.github.io"
title: "Cody Li"
favicon: "/img/favicon-fighter-jet.ico"
black-favicon: "/img/favicon-space-shuttle.ico"
#google-tracking-id: 
disqus-shortname: "codyli"
permalink: /blog/:categories/:title/


github-info:
  handle: "cl305"
  repo-desc-char-limit: 50
  repo-display-limit: 2

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About Me: 'about'
  #Music: 'music'
  Repos: "repos"
  Blog: 'blog'
  #Tech: "tech"
  Timeline: 'career'
  Contact: 'contact'

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True	
loop-count:	False #Set False for infinite loop, or set any number for finite loop.
type-speed:	10		#Default 10
start-delay: 200	#Default 200
delete-delay: 5000	#Default 5000
lines:			# You can add HTML Tags in the Text
- text: "Hi, I'm Cody!"

background-img: ""

# About variables

me-img: "/img/me2.jpg"
me-img-alt-text: "Cody Li"
# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 32

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
	- image: "/img/career/c1200x200.png"
		image-alt-text: "Capital One"
		date: "Jun 2017 - Aug 2017"
		description: "Data engineering intern"
	
	- image: "/img/career/hackduke320x320.jpg" 
		image-alt-text: "HackDuke"
		date: "March 2016 - Present"
		description: "Organizer, HackDuke"
	
  - image: "/img/career/dukeRoboticsRS.png"
    image-alt-text: "Duke Robotics"
    date: "Sept 2015 - December 2016"
    description: "Duke Robotics, electronics specialist"

  - image: "/img/career/dukePratt.jpeg"
    image-alt-text: "Duke Research"
    date: "Jun 2015 - December 2015"
    description: "Undergraduate engineering researcher, computer architecture"   

  - image: "/img/career/dukeRS.jpg"
    image-alt-text: "Duke University"
    date: "Aug 2014 - present"
    description: "B.S. Computer Science"

  - image: "/img/career/gswRS.jpg"
    image-alt-text: "Governor's School of North Carolina"
    date: "June 2014 - Jul 2014"
    description: "Governor's School West - Mathematics"

# First image of the Career timeline
career-img: "/img/career/duke400x400.jpeg"
career-img-alt-text: "Cody's Timeline"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "github"
    url: "https://github.com/cl305"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/cody-li-1127b9a4"
	- title: "instagram"
		url: "instagram.com/cody_li"

  
404-img: "/img/404.gif"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]


gems:
  - jekyll-sitemap
  - jekyll-redirect-from