# Site settings
protocol: "https:"
domain: "prashantsolanki3.github.io"
url: "https://prashantsolanki3.github.io"
title: "{ Prashant Solanki }"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-55643409-4"
disqus-shortname: "prashantsolanki3"
soundcloud_layout_type: "2"
permalink: /blog/:categories/:title/


github-info:
  handle: "prashantsolanki3"
  repo-desc-char-limit: 50
  repo-display-limit: 2

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Music: 'music'
  Repos: "repos"
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True	
loop-count:	False #Set False for infinite loop, or set any number for finite loop.
type-speed:	10		#Default 10
start-delay: 200	#Default 200
delete-delay: 5000	#Default 5000
lines:			# You can add HTML Tags in the Text
- text: "The lower you fall, the higher you'll fly."
- text: "May the wind under your wings bear you where the sun sails and the moon walks."
- text: "Some people never go crazy. What truly horrible lives they must lead."
- text: "Where’s your will to be weird?"

background-img: ""

# About variables

me-img: "/img/me.jpg"
me-img-alt-text: "Prashant Solanki"
# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 64

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/kakcho.jpg"
    image-alt-text: "Kakcho"
    date: "March 2015 - Today"
    description: "Head Developer @ <a href=\"http://kakcho.com\" target=\"_blank\">Kakcho</a>, working on Kakcho Android Application."
  - image: "/img/career/phoenix.jpg"
    date: "November 2014 - March 2015"
    description: "Created Phoenix Framework to make Mobile Application of Wordpress Blogs"
  - image: "/img/career/avyam.jpg"
    image-alt-text: "Avyam Technologies"
    date: "June 2014 - August 2014"
    description: "Internship @ <a href=\"http://http://www.avyamtechnologies.com\" target=\"_blank\">Avyam Technologies</a>, Android App Development"
  - image: "/img/career/gift-paradise.jpg"
    image-alt-text: "Gift Paradise"
    date: "March 2014 - June 2014"
    description: "Created Gift Paradise Android Application."
  - image: "/img/career/msit.jpg"
    image-alt-text: "Maharaja Surajmal Institute of Technology"
    date: "2013 - Pursuing"
    description: "Bachelor studies @ Maharaja Surajmal Institute of Technology, in Computer Science Branch"
  - image: "/img/career/bbps.jpg"
    image-alt-text: "Bal Bharati Public School"
    date: "2013"
    description: "CBSE XII Board @ Bal Bharati Public School"
  - image: "/img/career/bbps.jpg"
    image-alt-text: "Bal Bharati Public School"
    date: "2011"
    description: "CBSE X @ Bal Bharati Public School"
# First image of the Career timeline
career-img: "/img/career/default.jpg"
career-img-alt-text: "Prashant Solanki's Career"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/prashantsolanki3"
  - title: "linkedin"
    url: "http://in.linkedin.com/in/prashantsolanki3"
  - title: "bitbucket"
    url: "https://bitbucket.org/prashantsolanki"
  - title: "soundcloud"
    url: "https://soundcloud.com/prashantsolanki"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]


gems:
  - jekyll-sitemap
  - jekyll-redirect-from