# Site settings
protocol: "https:"
domain: "cl305.github.io"
url: "https://cl305.github.io"
title: "[ Cody Li ]"
favicon: "/img/favicon-fighter-jet.ico"
black-favicon: "/img/favicon-space-shuttle.ico"
#google-tracking-id: 
disqus-shortname: "codyli"
permalink: /blog/:categories/:title/


github-info:
  handle: "cl305"
  repo-desc-char-limit: 50
  repo-display-limit: 2

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  #Music: 'music'
  Repos: "repos"
  Blog: 'blog'
  Tech: "tech"
  Career: 'career'
  Contact: 'contact'

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True	
loop-count:	False #Set False for infinite loop, or set any number for finite loop.
type-speed:	10		#Default 10
start-delay: 200	#Default 200
delete-delay: 5000	#Default 5000
lines:			# You can add HTML Tags in the Text
- text: "Hey, I'm Cody."
- text: "They don't think it be like it is, but it do. - Oscar Gamble"


background-img: ""

# About variables

me-img: "/img/me.jpg"
me-img-alt-text: "Cody Li"
# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 64

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/dukeRS.jpg"
    image-alt-text: "Duke University"
    date: "Aug 2014 - present"
    description: "B.S.E. and B.S. in Electrical Computer Engineering and Computer Science"
  - image: "/img/career/gswRS.jpg"
    image-alt-text: "Governor's School of North Carolina"
    date: "June 2014 - Jul 2014"
    description: "Governor's School West - Mathematics"
  - image: "/img/career/dsa.jpg"
    image-alt-text: "Durham School of the Arts"
    date: "Aug 2010 - May 2014"
    description: "High school - Concentration in Violin"  
# First image of the Career timeline
career-img: "/img/startShoe.jpg"
career-img-alt-text: "Cody's Timeline"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "github"
    url: "https://github.com/cl305"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/cody-li-1127b9a4"

  

404-img: "/img/404.gif"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]


gems:
  - jekyll-sitemap
  - jekyll-redirect-from