
# Site settings

url: "https://panossakkos.github.io"
baseurl: ""
google-tracking-id: "UA-35880426-3"
force-https: True

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "Panos Sakkos"
lang: "en"
title: "{ Panos Sakkos }"
favicon: "/img/favicon.ico"
description: "Blog of Panos Sakkos, blogging mainly about tech. Opinions expressed are mine."
keywords: "panos, sakkos, technology, computer science, Pwn Mail, WriteRight, UoA, di, CERN, MDCN, Microsoft, Office Graph, Machine Learning, Databases, jekyll"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/me.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: Flase	# Shuffle the lines.
loop: False
loop-count:	1 # Set False for infinite loop, or set any number for finite loop.
type-speed:	4		# Default 10
start-delay: 2000	# Default 200
delete-delay: 50000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Why so serious?"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
linkedin-share: False
google-plus-share: False
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/microsoft.jpg"
    date: "September 2014 - Today"
    description: "Software Engineer @ Microsoft Development Center Norway, working @ the <a href=\"https://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"
  - image: "/img/career/microsoft.jpg"
    date: "June 2013 - September 2013"
    description: "Software Engineering Intern @ Microsoft Development Center Norway, worked @ the <a href=\"https://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"
  - image: "/img/career/uoa.jpg"
    date: "October 2012 - August 2014"
    description: "Master studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Software Engineering + <a href=\"https://scholar.google.com/citations?user=UtV6LFYAAAAJ&amp;hl=en&amp;oi=ao\" target=\"_blank\">Machine Learning researcher</a> @ <a href=\"http://kddlab.di.uoa.gr\" target=\"_blank\">KDD</a> lab"
  - image: "/img/career/cern.jpg"
    date: "October 2011 - September 2012"
    description: "Security researcher @ <a href=\"https://www.cern.ch\" target=\"_blank\">CERN</a>, developed linux kernel extensions to prevent cyber attacks"
  - image: "/img/career/pwnmail.jpg"
    date: "June 2010 - November 2010"
    description: "Created <a href=\"https://www.google.com/search?q=pwn+mail\" target=\"_blank\">Pwn Mail</a>, a Cydia iPhone app for spoofing emails. It served &gt; 260,000 emails but it was discontinued after a legal threat by Steve Jobs"
  - image: "/img/career/uoa.jpg"
    date: "October 2007 - September 2011"
    description: "Bachelor studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Computer Science and Telecomunications"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

##################
# Contact layout #
##################

email: "panoss@microsoft.com"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/PanosSakkos"
  - title: "linkedin"
    url: "https://no.linkedin.com/in/PanosSakkos"
  - title: "twitter"
    url: "https://twitter.com/thepanoss"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables bellow this point!

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems: [jekyll-paginate]
